runtime: python
env: flex

runtime_config:
  operating_system: "ubuntu22"
  python_version: "3.12"

entrypoint: streamlit run app.py --server.port $PORT

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 15
