env: standard
runtime: python312

entrypoint: gunicorn -b 0.0.0.0:8080 layouts:server

basic_scaling:
    max_instances: 1
    idle_timeout: 2m

resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 10
